# Makefile for the AW_Config
#
# @author Marcelo Coraça de Freitas <marcelo.batera@gmail.com> 


libs:
	gnatmake -P awconfig.gpr
tests: libs
	gnatmake -P awconfig-tests.gpr

all: libs


run-xml: tests
	TEST_CONFIG_PATH=$(PWD)/data ./bin/xml-test


run-plain: tests
	TEST_CONFIG_PATH=$(PWD)/data ./bin/plain-test

run: run-xml run-plain


clean-libs:
	gnatclean -P awconfig.gpr
clean-tests:
	gnatclean -P awconfig-tests.gpr
clean: clean-tests clean-libs
	@echo "All clean"



docs:
	@-./gendoc.sh
	@echo "The documentation is generated by a bash script. Then it might fail in other platforms"
