# Makefile for the AW_Config
#
# @author Marcelo Coraça de Freitas <marcelo.batera@gmail.com> 

all: parsers

base:
	ADA_PROJECT_PATH=.:../awlib gnatmake -P awconfig.gpr

text-parser: base
	ADA_PROJECT_PATH=.:../awlib gnatmake -P awconfig-text_parser.gpr
	
xml-parser: base
	ADA_PROJECT_PATH=.:../awlib gnatmake -P awconfig-xml_parser.gpr `xmlada-config`

parsers: text-parser xml-parser


text-test: text-parser
	ADA_PROJECT_PATH=.:../awlib gnatmake -P awconfig-text_test.gpr

xml-test: xml-parser
	ADA_PROJECT_PATH=.:../awlib gnatmake -P awconfig-xml_test.gpr

tests: text-test xml-test

run-xml: tests
	TEST_CONFIG_PATH=$(PWD)/data ./bin/xml-test


run-plain: tests
	TEST_CONFIG_PATH=$(PWD)/data ./bin/plain-test

run: run-xml run-plain


clean-base:
	ADA_PROJECT_PATH=.:../awlib gnatclean -P awconfig.gpr
clean-parsers:	
	ADA_PROJECT_PATH=.:../awlib gnatclean -P awconfig-parsers.gpr
clean-tests:
	ADA_PROJECT_PATH=.:../awlib gnatclean -P awconfig-tests.gpr

clean: clean-tests clean-parsers clean-base 
	@rm bin/* lib/* obj/*
	@echo "All clean"



docs:
	@-./gendoc.sh
	@echo "The documentation is generated by a bash script. Then it might fail in other platforms"
